##  程序的错误可以分为两种:
    1.error   stackoverflowError
        出现严重错误的 一般是不针对代码进行处理的  而是对程序或者外部环境进行修正   大部分是虚拟机的问题
    
    
    2.Exception  可以人为解决的错误
                a.编译时异常   ....
                    
                b.运行时异常   ....
         
         对异常的 处理:
            try{
                }
            catch(){
            
            }
         try{
         
         }finally{
         
         }
        try{
        
        }catch(){
        
        }finally{
        
        }
        
        
        throws  和 throw  区别:
            用在方法声明后面 跟的是异常的类名
            可以跟多个异常
            表示跑出的异常由调用者来处理
            Throws 表示出现的异常只是一种可能性   并不一定会发生这个异常
            
           
           throw 
                用在方法体内  跟的异常对象的名
                只能跟一个异常对象名
                表示抛出的异常有方法体内的语句处理
                throw是抛出异常  执行到throw  则一定抛出某种异常 
            
            
###异常的注意事项
1.子类重写父类的方法的时候 子类方法 必须抛出相同的异常或者是父类异常的子类
2.如果父类抛出多个异常 子类重写父类的方法时,只能抛出相同的异常或者是他的子集,子类不能抛出父类没有异常
3.如果被重写的方法没有异常抛出,那么子类的方法绝对不可以抛出异常 如果子类有异常发生,那么只能只能try捕捉 不能throws 抛出  
            
 
##  什么是断言？   关键字 assert 
    主要是用于代码的测试和开发时期 对一些关键性的数据进行判断
    如果满足条件则进行执行程序  如果不满足条件   则程序会抛出一个断言异常  并且有警告提醒
    if(exprission){
        
    }else{
    
    }
    
    
    
    
    
    
    
    
    
    
            
            
            
            